daysUntilStale: 60

daysUntilClose: 7

exemptLabels:
  - enhancement
  - security

exemptMilestones: true
exemptProjects: true

staleLabel: stale

markComment: >
  This issue has been [automatically marked as stale](https://probot.github.io/apps/stale/#how-it-works)
  because it has not had recent activity. It will be closed in 7 days if no
  further activity occurs. Thank you for your contributions.